[package]
name = "agar"
version = "0.0.1"
edition = "2021"
license = "GPL3"
authors = ["wick3dr0se <wick3dr0se@protonmail.com>"]
repository = "https://github.com/wick3dr0se/agar"

[dependencies]
macroquad = "0.4.13"
